---
- name: Configuration postgresql.conf
  lineinfile:
    line: "{{ item.name }} = '{{ item.value }}'"
    state: "{{ item.state|default('present') }}"
    dest: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
  notify: restart postgres
  with_items: "{{ postgres_settings }}"

- name: Configuration pg_hba
  lineinfile:
    line: "{{ item.value }}"
    state: "{{ item.state|default('present') }}"
    dest: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
  notify: reload postgres
  with_items: "{{ postgres_hba_settings }}"
