---
- name: Check CA certificates
  apt:
    pkg: ca-certificates
    state: present

- name: Add PostgreSQL repository apt-key
  apt_key:
    id: "{{ postgres_apt_key_id }}"
    url: "{{ postgres_apt_key_url }}"
    state: present

- name: Add PostgreSQL repository
  apt_repository:
    repo: "{{ postgres_apt_repository }}"
    state: present
  notify: update apt cache

- meta: flush_handlers

- name: Install PostgreSQL
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - "postgresql-{{ postgres_version }}"
    - "postgresql-client-{{ postgres_version }}"
    - "postgresql-contrib-{{ postgres_version }}"

- name: Install psycopg2
  apt:
    name: "python-psycopg2"
    state: present
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  when: postgres_users or postgres_databases
