---
- name: restart postgres
  service:
    name: "postgresql"
    state: restarted

- name: reload postgres
  service:
    name: "postgresql"
    state: reloaded

- name: update apt cache
  apt:
    update_cache: 'yes'
